#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 07, 2018 10:34:48 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import startupcustomizer_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    startupcustomizer_support.set_Tk_var()
    top = Startup_Customizer (root)
    startupcustomizer_support.init(root, top)
    root.mainloop()

w = None
def create_Startup_Customizer(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    startupcustomizer_support.set_Tk_var()
    top = Startup_Customizer (w)
    startupcustomizer_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Startup_Customizer():
    global w
    w.destroy()
    w = None


class Startup_Customizer:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {DejaVu Sans} -size 16 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font9 = "-family {DejaVu Sans} -size 11 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("537x513+605+204")
        top.title("Startup-Customizer")
        top.configure(background="#5888d8")
        top.configure(highlightcolor="black")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.08, rely=0.29, height=68, width=446)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="#5888d8")
        self.Label1.configure(font=font10)
        self.Label1.configure(text='''Enter Command to run at Statup''')

        self.command_app = Entry(top)
        self.command_app.place(relx=0.09, rely=0.41,height=60, relwidth=0.83)
        self.command_app.configure(background="white")
        self.command_app.configure(font="TkFixedFont")
        self.command_app.configure(selectbackground="#c4c4c4")
        self.command_app.configure(textvariable=startupcustomizer_support.command)

        self.Button1 = Button(top)
        self.Button1.place(relx=0.3, rely=0.6, height=46, width=217)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(command=startupcustomizer_support.addapp)
        self.Button1.configure(font=font9)
        self.Button1.configure(state=ACTIVE)
        self.Button1.configure(text='''Add on Startup''')

        self.Button1_1 = Button(top)
        self.Button1_1.place(relx=0.05, rely=0.81, height=46, width=217)
        self.Button1_1.configure(activebackground="#d9d9d9")
        self.Button1_1.configure(command=startupcustomizer_support.viewaddedapps)
        self.Button1_1.configure(font=font9)
        self.Button1_1.configure(text='''View Added Apps''')

        self.Button1_2 = Button(top)
        self.Button1_2.place(relx=0.56, rely=0.81, height=46, width=217)
        self.Button1_2.configure(activebackground="#d9d9d9")
        self.Button1_2.configure(command=startupcustomizer_support.deleteapps)
        self.Button1_2.configure(font=font9)
        self.Button1_2.configure(text='''Delete Added Apps''')

        self.Label1_3 = Label(top)
        self.Label1_3.place(relx=0.07, rely=0.02, height=68, width=446)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(background="#5888d8")
        self.Label1_3.configure(font=font10)
        self.Label1_3.configure(text='''Enter Name of Application''')

        self.name_of_app = Entry(top)
        self.name_of_app.place(relx=0.27, rely=0.16,height=50, relwidth=0.42)
        self.name_of_app.configure(background="white")
        self.name_of_app.configure(font="TkFixedFont")
        self.name_of_app.configure(selectbackground="#c4c4c4")
        self.name_of_app.configure(textvariable=startupcustomizer_support.name_of_app)

        self.Button2 = Button(top)
        self.Button2.place(relx=0.83, rely=0.33, height=26, width=53)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(background="#5888d8")
        self.Button2.configure(command=startupcustomizer_support.help)
        self.Button2.configure(relief=FLAT)
        self.Button2.configure(text='''(Help?)''')
        self.Button2.configure(width=53)






if __name__ == '__main__':
    vp_start_gui()



